# MPE Evaluation

This runs the trained MAPPO policy for goal navigation.

In [1]:
import sys
import os

project_root = "/Users/yaoliu/Desktop/Fair-MARL"
if project_root not in sys.path:
    sys.path.append(project_root)

In [2]:
model_dir = os.path.join(
    project_root,
    "onpolicy/results/GraphMPE/nav_fairassign_nofairrew_formation_graph/rmappo/test123/wandb/run-20250731_203942-zy37uwpj/files"
)

## Configuration

In [ ]:
from onpolicy.scripts.eval_mpe import main
notebook_args = [
    "--env_name", "GraphMPE",
    "--scenario_name", "nav_fairassign_nofairrew_formation_graph",
    "--algorithm_name", "rmappo",
    "--model_dir", model_dir,
    "--assignment_type", "fair",
    "--use_fairness_reward",
    "--num_agents", "2",
    "--num_landmarks", "2",
    "--num_obstacles", "2",
    "--world_size", "3",
    "--episode_length", "500",
    "--render_episodes", "5",
    "--save_gifs",
    "--use_render",
    "--max_speed", "0.01"
]



In [4]:
main(notebook_args)

__________________________________________________
Using fair_rew = 1
Using min_obs_dist = 0.5
Using model_name = FA_FR
Using seed = 1
Using world_size = 3.0
Using max_edge_dist = 1
Using num_walls = 0
Using episode_length = 500
Using save_gifs = True
Using use_render = True
Using render_episodes = 5
Using model_dir = /Users/yaoliu/Desktop/Fair-MARL/onpolicy/results/GraphMPE/nav_fairassign_nofairrew_formation_graph/rmappo/test123/wandb/run-20250731_203942-zy37uwpj/files
Using scenario_name = nav_fairassign_nofairrew_formation_graph
Using num_landmarks = 2
Using num_agents = 2
Using num_obstacles = 2
Using collaborative = False
Using goal_rew = 20
Using min_dist_thresh = 0.05
Using use_dones = True
__________________________________________________


/opt/homebrew/Caskroom/miniconda/base/envs/fairmarl/lib/python3.9/site-packages/cvxpy/reductions/solvers/solving_chain.py:336: FutureWarning: 
    Your problem is being solved with the ECOS solver by default. Starting in 
    CVXPY 1.5.0, Clarabel will be used as the default solver instead. To continue 
    using ECOS, specify the ECOS solver explicitly using the ``solver=cp.ECOS`` 
    argument to the ``problem.solve`` method.
    
  warnings.warn(ECOS_DEPRECATION_MSG, FutureWarning)
/opt/homebrew/Caskroom/miniconda/base/envs/fairmarl/lib/python3.9/site-packages/torch_geometric/typing.py:31: UserWarning: An issue occurred while importing 'torch-scatter'. Disabling its usage. Stacktrace: dlopen(/opt/homebrew/Caskroom/miniconda/base/envs/fairmarl/lib/python3.9/site-packages/torch_scatter/_version_cpu.so, 0x0006): symbol not found in flat namespace '__ZN3c106detail14torchCheckFailEPKcS2_jRKSs'
  warnings.warn(f"An issue occurred while importing 'torch-scatter'. "
/opt/homebrew/Caskroom/m

x_val shape: [[9.99999998e-01 1.46688926e-10]
 [1.21929429e-09 9.99999999e-01]]
one_hot shape: [[1. 0.]
 [0. 1.]]
[Agent 0] Relative feature relative to Agent 0: [ 0.          0.          0.          0.          0.90784462 -0.39961702
  0.         -1.          0.          0.          0.          0.
 -1.          0.          0.        ]
[Agent 0] Relative feature relative to Agent 1: [ 0.          0.          0.57976802  0.06728112  0.90784462 -0.39961702
  0.         -1.          0.57976802  0.06728112  0.57976802  0.06728112
 -1.          0.          0.        ]
[Agent 0] Relative feature relative to landmark 0: [ 0.          0.          0.90784462 -0.39961702  0.90784462 -0.39961702
  1.          0.          0.90784462 -0.39961702  0.90784462 -0.39961702
  0.          1.          2.        ]
[Agent 0] Relative feature relative to landmark 1: [ 0.          0.          1.37079967 -0.8245722   1.37079967 -0.8245722
  1.          1.          1.37079967 -0.8245722   1.37079967 -0.8245722


/opt/homebrew/Caskroom/miniconda/base/envs/fairmarl/lib/python3.9/site-packages/torch/cuda/amp/grad_scaler.py:120: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.")
/opt/homebrew/Caskroom/miniconda/base/envs/fairmarl/lib/python3.9/site-packages/cvxpy/reductions/solvers/solving_chain.py:336: FutureWarning: 
    Your problem is being solved with the ECOS solver by default. Starting in 
    CVXPY 1.5.0, Clarabel will be used as the default solver instead. To continue 
    using ECOS, specify the ECOS solver explicitly using the ``solver=cp.ECOS`` 
    argument to the ``problem.solve`` method.
    
  warnings.warn(ECOS_DEPRECATION_MSG, FutureWarning)


Set parameter WLSAccessID
Set parameter WLSSecret
Set parameter LicenseID to value 2688516
Academic license 2688516 - for non-commercial use only - registered to jl___@usc.edu
[solve_fair_assignment] Iter 1/2:
  Costs matrix:
 [[1.175848   1.39027751]
 [0.34790179 0.88624197]]
  Solver status: ok
  Termination condition: optimal
[solve_fair_assignment] Iter 2/2:
  Costs matrix:
 [[1.175848   1.39027751]
 [0.34790179 0.88624197]]
  Solver status: ok
  Termination condition: optimal
[Agent 0] Relative feature relative to Agent 0: [ 0.          0.          0.          0.          0.7472862   0.90784462
  0.65209821 -1.          0.          0.          0.          0.
 -1.          0.          0.        ]
[Agent 0] Relative feature relative to Agent 1: [ 5.06991556e-12 -4.17549575e-12  6.31521789e-01  5.79768021e-01
  7.47286200e-01  9.07844620e-01  6.52098212e-01 -1.00000000e+00
  6.31521789e-01  5.79768021e-01  6.31521789e-01  5.79768021e-01
 -1.00000000e+00  0.00000000e+00  0.00000000e+0

/opt/homebrew/Caskroom/miniconda/base/envs/fairmarl/lib/python3.9/site-packages/cvxpy/reductions/solvers/solving_chain.py:336: FutureWarning: 
    Your problem is being solved with the ECOS solver by default. Starting in 
    CVXPY 1.5.0, Clarabel will be used as the default solver instead. To continue 
    using ECOS, specify the ECOS solver explicitly using the ``solver=cp.ECOS`` 
    argument to the ``problem.solve`` method.
    
  warnings.warn(ECOS_DEPRECATION_MSG, FutureWarning)


[solve_fair_assignment] Iter 1/2:
  Costs matrix:
 [[2.08090721 1.29517774]
 [1.76242952 0.73715544]]
  Solver status: ok
  Termination condition: optimal
[solve_fair_assignment] Iter 2/2:
  Costs matrix:
 [[2.08090721 1.29517774]
 [1.76242952 0.73715544]]
  Solver status: ok
  Termination condition: optimal
[Agent 0] Relative feature relative to Agent 0: [ 0.          0.          0.          0.          0.59763527  1.14905068
  0.         -1.          0.          0.          0.          0.
 -1.          0.          0.        ]
[Agent 0] Relative feature relative to Agent 1: [ 1.92627607e-10 -2.38242126e-10 -1.61285588e-02  1.55733012e+00
  5.97635272e-01  1.14905068e+00  0.00000000e+00 -1.00000000e+00
 -1.61285588e-02  1.55733012e+00 -1.61285588e-02  1.55733012e+00
 -1.00000000e+00  0.00000000e+00  0.00000000e+00]
[Agent 0] Relative feature relative to landmark 0: [ 1.92624020e-10 -2.38241671e-10 -1.73173948e+00  1.15379946e+00
 -1.73173948e+00  1.15379946e+00  1.00000000e+00  0.00000